*** Starting uWSGI 2.0.21 (64bit) on [Fri Aug 25 13:07:13 2023] ***
compiled with version: 11.2.0 on 28 March 2023 07:25:39
os: Linux-5.4.0-139-generic #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023
nodename: VM-8-13-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/summer/summer_backend
writing pidfile to uwsgi.pid
detected binary path: /home/summer/miniconda3/envs/django/bin/uwsgi
chdir() to /home/summer/summer_backend
your processes number limit is 7547
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8000).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.21 (64bit) on [Fri Aug 25 13:08:13 2023] ***
compiled with version: 11.2.0 on 28 March 2023 07:25:39
os: Linux-5.4.0-139-generic #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023
nodename: VM-8-13-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/summer/summer_backend
writing pidfile to uwsgi.pid
detected binary path: /home/summer/miniconda3/envs/django/bin/uwsgi
chdir() to /home/summer/summer_backend
your processes number limit is 7547
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 6
Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0]
Set PythonHome to /home/summer/miniconda3/envs/django
Python main interpreter initialized at 0x20bbee0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
added /home/summer/miniconda3/envs/django/lib/python3.9/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x20bbee0 pid: 2567136 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2567136)
spawned uWSGI worker 1 (pid: 2567145, cores: 2)
spawned uWSGI worker 2 (pid: 2567147, cores: 2)
spawned uWSGI worker 3 (pid: 2567148, cores: 2)
spawned uWSGI worker 4 (pid: 2567150, cores: 2)
Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/base.py", line 313, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./summer_backend/urls.py", line 21, in <module>
    path('api/user/', include('user.urls')),
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./user/urls.py", line 5, in <module>
    from . import views
  File "/home/summer/summer_backend/./user/views.py", line 18, in <module>
    from jose import JWTError
ModuleNotFoundError: No module named 'jose'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./summer_backend/urls.py", line 21, in <module>
    path('api/user/', include('user.urls')),
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./user/urls.py", line 5, in <module>
    from . import views
  File "/home/summer/summer_backend/./user/views.py", line 18, in <module>
    from jose import JWTError
ModuleNotFoundError: No module named 'jose'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./summer_backend/urls.py", line 21, in <module>
    path('api/user/', include('user.urls')),
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./user/urls.py", line 5, in <module>
    from . import views
  File "/home/summer/summer_backend/./user/views.py", line 18, in <module>
    from jose import JWTError
ModuleNotFoundError: No module named 'jose'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./summer_backend/urls.py", line 21, in <module>
    path('api/user/', include('user.urls')),
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./user/urls.py", line 5, in <module>
    from . import views
  File "/home/summer/summer_backend/./user/views.py", line 18, in <module>
    from jose import JWTError
ModuleNotFoundError: No module named 'jose'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./summer_backend/urls.py", line 21, in <module>
    path('api/user/', include('user.urls')),
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./user/urls.py", line 5, in <module>
    from . import views
  File "/home/summer/summer_backend/./user/views.py", line 18, in <module>
    from jose import JWTError
ModuleNotFoundError: No module named 'jose'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./summer_backend/urls.py", line 21, in <module>
    path('api/user/', include('user.urls')),
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./user/urls.py", line 5, in <module>
    from . import views
  File "/home/summer/summer_backend/./user/views.py", line 18, in <module>
    from jose import JWTError
ModuleNotFoundError: No module named 'jose'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./summer_backend/urls.py", line 21, in <module>
    path('api/user/', include('user.urls')),
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./user/urls.py", line 5, in <module>
    from . import views
  File "/home/summer/summer_backend/./user/views.py", line 18, in <module>
    from jose import JWTError
ModuleNotFoundError: No module named 'jose'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./summer_backend/urls.py", line 21, in <module>
    path('api/user/', include('user.urls')),
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./user/urls.py", line 5, in <module>
    from . import views
  File "/home/summer/summer_backend/./user/views.py", line 18, in <module>
    from jose import JWTError
ModuleNotFoundError: No module named 'jose'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./summer_backend/urls.py", line 21, in <module>
    path('api/user/', include('user.urls')),
  File "/home/summer/miniconda3/envs/django/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/summer/miniconda3/envs/django/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/summer/summer_backend/./user/urls.py", line 5, in <module>
    from . import views
  File "/home/summer/summer_backend/./user/views.py", line 18, in <module>
    from jose import JWTError
ModuleNotFoundError: No module named 'jose'
[pid: 2567150|app: 0|req: 1/1] 219.239.227.218 () {40 vars in 697 bytes} [Fri Aug 25 13:08:51 2023] POST /api/user/register/ => generated 0 bytes in 3444 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
[pid: 2567150|app: 0|req: 2/2] 219.239.227.218 () {40 vars in 697 bytes} [Fri Aug 25 13:10:22 2023] POST /api/user/register/ => generated 59 bytes in 1736 msecs (HTTP/1.1 200) 7 headers in 212 bytes (1 switches on core 1)
[pid: 2567150|app: 0|req: 3/3] 134.209.22.239 () {40 vars in 1126 bytes} [Fri Aug 25 13:11:44 2023] GET /api/user/activate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6IjI2Mjk2MzY2NzRAcXEuY29tIiwidGltZXN0YW1wIjoxNjkyOTQwMjIzfQ.UOGI1rujvyOwxW6nQ0KgYs8rqEXAn9RkpzhOkvGzWAk => generated 0 bytes in 7 msecs (HTTP/1.1 301) 3 headers in 287 bytes (1 switches on core 0)
[pid: 2567150|app: 0|req: 4/4] 134.209.22.239 () {40 vars in 1128 bytes} [Fri Aug 25 13:11:45 2023] GET /api/user/activate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6IjI2Mjk2MzY2NzRAcXEuY29tIiwidGltZXN0YW1wIjoxNjkyOTQwMjIzfQ.UOGI1rujvyOwxW6nQ0KgYs8rqEXAn9RkpzhOkvGzWAk/ => generated 3469 bytes in 29 msecs (HTTP/1.1 200) 7 headers in 222 bytes (1 switches on core 1)
Not Found: /api/user/activate/static/images/logo.png
[pid: 2567150|app: 0|req: 5/5] 134.209.22.239 () {38 vars in 918 bytes} [Fri Aug 25 13:11:46 2023] GET /api/user/activate/static/images/logo.png => generated 3244 bytes in 5 msecs (HTTP/1.1 404) 7 headers in 229 bytes (1 switches on core 0)
